### ISSUE TITLE
Lambda Functions Not Working in FlexBE Web UI

### ISSUE THREAD

**Issue by RPRKLR** [FlexBE/flexbe_webui#2]
**Title:** Lambda Functions Not Working in FlexBE Web UI

**Description:**
I have been using ROS2 with the flexbe_app, and in that environment, lambda functions worked correctly. They also functioned as expected in ROS1. However, I am now using the flexbe_webui, and when I try to load behaviors that include lambda functions, I encounter several issues.

**Steps to Reproduce:**
1. Use flexbe_app with ROS2 to create a behavior that includes lambda functions.
2. Attempt to load the same behavior in flexbe_webui.

**Expected Behavior:**
- The lambda functions should be correctly parsed and executed as they were in the flexbe_app environment for both ROS1 and ROS2.

**Actual Behavior:**
- Initially, an error is thrown: `TypeError: Cannot read properties of undefined (reading 'match')`.
- If the lambda functions are fed as strings, the behaviors can be loaded, but the lambda functions do not work.

**Example Case:**
Here is a simple example demonstrating the issue:

In flexbe_app with ROS2:
```python
OperatableStateMachine.add('IsOrder',
                           CheckConditionState(predicate=lambda x: x == 'sample-order'),
                           transitions={'true': 'SampleTimeout', 'false': 'CustomTimeout'},
                           autonomy={'true': Autonomy.Off, 'false': Autonomy.Off},
                           remapping={'input_value': 'order_type'})
```
When changing the lambda as a string it can load the states, and the behaviors, but the lambda function does not run as it should. This is how the code looks when feeding the lambda as a string:
```python
OperatableStateMachine.add('IsOrder',
                           CheckConditionState(predicate="lambda x: x == 'sample-order'"),
                           transitions={'true': 'SampleTimeout', 'false': 'CustomTimeout'},
                           autonomy={'true': Autonomy.Off, 'false': Autonomy.Off},
                           remapping={'input_value': 'order_type'})
```
This issue only happens for `webui`. 

**Environment:**
- **ROS2 Iron**
- **FlexBE Web UI version: 0.0.0** 
- **OS: Ubuntu 22.04**

**Comment by dcconner** [comment]
I'll look into this tonight.  Thanks for the report.  Can you send me a screen shot of your entry box under the webui.

**Comment by dcconner** [comment]
I believe this is fixed with the latest push to beta.  @RPRKLR please take a look and let me know.

We are trying to do more prevalidation on inputs, and provide notice of how types are interpreted (more in documentation coming this summer).  I have simplified the equation test, and it seems more flexible now.  Let me know if this is working for you now.

**Comment by RPRKLR** [comment]
Does the lambda function needs to be loaded as a string?

**Comment by dcconner** [comment]
No.   Type it in without quotes.

**Comment by RPRKLR** [comment]
The lambdas are working, when I enter them without quotes. But when I save the behavior, when I try to load it, I still get the error that `Code parsing failed: TypeError: Cannot read properties of undefinied (reading 'match')`

![flexbe_parsing_issue](https://github.com/FlexBE/flexbe_webui/assets/83779344/e738f767-679e-405e-9f9f-674038e78e05)

**Comment by RPRKLR** [comment]
The issue is that I have two types of lambda functions, it can load the first type, which looks like this:
```python
lambda x : self.switch_off_timer
```
It can not load the lambda if it is checking a string, for example:
```python
lambda x: x=='is_navigating'
```

**Comment by dcconner** [comment]
Confirmed the issue.  I thought the issue was caused by something else, and in my late night testing I did not try to re-start and reload as I was focused on execution of behavior after saving.  I can confirm the error is happening on my end, but it will be tomorrow night before I have time to fully understand and fix.

**Comment by dcconner** [comment]
Pushed change that addresses this issue in my tests.

**Comment by RPRKLR** [comment]
Thanks for the support, I am still facing an issue. If the state only have one input, it works, but if the state have 2 inputs, like the `FlexibleCheckConditionState`, which have 2 inputs like `predicate` and `input_keys`,  get an error, which can be seen in the picture. 
![Screenshot from 2024-06-24 07-36-55](https://github.com/FlexBE/flexbe_webui/assets/83779344/86722a10-7363-4b6b-a9a7-04bfe4b8f79a)
I tried to put lambdas with quotes and lambda functions without quotes like `lambda x: x==self.is_waiting_for_service`, and none of them work.

**Comment by dcconner** [comment]
I have pushed some updates to flexbe_webui, and also flexbe_behavior_engine (ros2-devel) branch.  The BE changes include some tweaks to descriptions of parameters, and the webui includes some additional validation and clean up.

With these, I am able to use the the FlexibleCheckConditionState with complex lambdas.

![user_data_setup](https://github.com/FlexBE/flexbe_webui/assets/66255/12049a9b-a9a8-4f6f-ae76-92b6827172f0)
![flexible_condition_lambda](https://github.com/FlexBE/flexbe_webui/assets/66255/ffd4f3e0-7a24-4d38-9fce-13eaefc961a9)
![flexible_condition_setup](https://github.com/FlexBE/flexbe_webui/assets/66255/fbe6a797-3c0c-4731-9b9a-39851b2b8a06)

**Comment by RPRKLR** [comment]
I can create the `FlexibleCheckConditionState`, and I can set the parameters like on the picture:
![Screenshot from 2024-06-25 08-26-19](https://github.com/FlexBE/flexbe_webui/assets/83779344/1c155667-e552-4083-9afd-abad5e568086)
![Screenshot from 2024-06-25 08-26-31](https://github.com/FlexBE/flexbe_webui/assets/83779344/65fcfa2d-df95-4a02-b7a1-627c17853738)
And I can save and launch the behavior, and it works without a problem, but when I try to load the saved behavior, I get the following error:
`The loaded behavior contains errors! Please fis and save:`
`parameter predicate of state /IfServiceWaiting has empty value`
And also it can not load the transitions too, so it is not connected to other states.

**Comment by dcconner** [comment]
@RPRKLR Please give the latest a try.

**Comment by RPRKLR** [comment]
Now everything is working, as it should. Thank you for your support! The issue can be closed.

**Comment by dcconner** [comment]
Great!  Thank you for your detailed error reports and helpful testing.  I appreciate the input.
